#!/usr/bin/python2 -S
# -*- coding: utf-8 -*-
import sys
sys.setdefaultencoding("utf-8")
import site

# 工具入口


import parser 
from parser import report_parser

def print_usage():
    print "Usage:"
    print "  导入日报文件 -  %s import <日报文件>" % sys.argv[0]

# 处理 'import' 子命令
def handle_import( argv):
    i = len(argv)
    if ( i < 1 ):
        print "  导入日报文件 -  %s import <日报文件>" % sys.argv[0]
        print "\n 未指定 <日报文件>\n"
        return 1

    s = report_parser.parse_single_file( argv[0]  )

    if s is None:
        return 1

    s.dump()

    return 0

def main():

    i = len(sys.argv)
    if ( i < 2 ):
        print_usage()
        return 1

    sub_command = sys.argv[1]
    if ('import' == sub_command ):
        return handle_import ( sys.argv[2:] )
    else:
        print "\n无效的‘子命令’ -- %s\n" % ( sub_command, )
        print_usage()
        return 1

    return 0


if __name__ == "__main__":
    r = main()
    sys.exit(r)


